apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "csi-lvm.fullname" . }}
  labels:
    {{- include "csi-lvm.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - {{ include "csi-lvm.fullname" . }}
    verbs:
      - use
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
