apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "csi-lvm.fullname" . }}
  labels:
    {{- include "csi-lvm.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""
  resources:
    - nodes
    - persistentvolumeclaims
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - endpoints
    - persistentvolumes
    - pods
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - storage.k8s.io
  resources:
    - storageclasses
  verbs:
    - get
    - list
    - watch
