apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csi-lvm.fullname" . }}
  labels:
    {{- include "csi-lvm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "csi-lvm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.controller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "csi-lvm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "csi-lvm.fullname" . }}-controller
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-controller
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          command:
            - /csi-lvm-controller
          args:
            - start
          env:
            - name: CSI_LVM_PROVISIONER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CSI_LVM_PULL_POLICY
              value: {{ .Values.reviver.image.pullPolicy }}
            - name: CSI_LVM_PROVISIONER_IMAGE
              value: "{{ .Values.reviver.image.repository }}:{{ .Values.reviver.image.tag | default .Chart.AppVersion }}"
            - name: CSI_LVM_DEVICE_PATTERN
              value: "{{ .Values.controller.lvmDevicePattern }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
